### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by ninozhang** [v12/node-vk-api#4]
Why do I always get this error message?

Error: Invalid URI "/login.php?act=security_check&to=&hash=a936e4547b470c22b7&api_hash=5529f59f1723a4d1a1"]
Error: Invalid URI "/login.php?act=security_check&to=&hash=a936e4547b470c22b7&api_hash=5529f59f1723a4d1a1"
at Request.init (/path/node_modules/vk-dirty-api/node_modules/request/request.js:286:31)
at new Request (/path/node_modules/vk-dirty-api/node_modules/request/request.js:140:8)
at request (/path/node_modules/vk-dirty-api/node_modules/request/index.js:55:10)
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12
at /path/node_modules/vk-dirty-api/node_modules/request/index.js:101:12

**Comment by ninozhang** [comment]
is there anyone that can fix this problem?

**Comment by v12** [comment]
@ninozhang I've just finished working on this bug but will push changes as soon as I finish a logic for processing cases when security check is requested. ETA is 12 Dec.

**Comment by v12** [comment]
Should now be fixed in 6617b41f2ce9bbfeeb556e418be54e325169b771.

Apparently, it's not published to npm yet but will be as soon as I finish refactoring the library to use Promises. It means that #2 is a blocker right now. Currently, there are enough breaking changes that require major version update, however, I don't want to do it until #2 is closed.

@ninozhang would you mind to try version from master to see if it's working fine for you? Please note, that now it requires either login to be a phone number or, if it's not, separate `phone` option should be specified (it is the number, which is attached to an account for security purposes). Unfortunately, it is now compulsory to have phone number as a parameter just because I want to avoid people using this vk-dirty-api library for any kind of bad deeds.

Closing is it for now unless anyone has issues with that again.
