### ISSUE TITLE
Can I use the api without ES6

### ISSUE THREAD

**Issue by xiaokaike** [v12/node-vk-api#6]

**Comment by v12** [comment]
[Yes, you can](http://babeljs.io). However, I'd strongly **recommend** you to learn and use ES6 features when it's possible to do so. Have a look at [this tutorial](http://babeljs.io/docs/learn-es2015/)!

Node.js ecosystem philosophy is about continuous improvement and not stalling with something that is preventing yourself from writing nice and shiny code, which takes less time to write but stays as efficient as it was supposed to be. And, something even more important, easy to support.

I'm really not keen on supporting legacy systems just because it takes more time. Unfortunately, I don't have spare time to do that. But, even if I had, I wouldn't do that. Simply because it'll create more incentive for people to learn something new (well, not really new, but still).

Node.js has stable branch (v4 as of now), which is "mature and dependable" and has support for all ES6 features used within this module.

Improve yourself, broaden your knowledge – learn ES2015! :wink:

**Comment by xiaokaike** [comment]
thinks :wink:
